### ISSUE TITLE
[Feature Request] Show 'library' used for a style/symbol in inspector

### ISSUE THREAD

**Issue by josh-tt** [ingrammicro/puzzle-publisher#10]
Would be super useful to add the 'Source' for each element to the info pane, rather than (or in addition to) the library filter.

For example, when inspecting a style you would see:
Style : UI Background
Style Source: Carbon Design Theme (external)

Style: UI Background
Style Source: Document

Any chance you can add that feature? Would be super helpful to track down a style's origin and make corrections to it in Sketch. 

Alternatively, it would be nice to see a full table overview of all the styles, tokens and their library origin (similar to a spreadsheet).

Cheers and great work!

**Comment by MaxBazarov** [comment]
I glad to know that at least you are using both plugins in integration.
I think it's possible to show style source.

About full overview — sure, it's possible. But it needs more time to design and develop it. I will investigate it.

**Comment by MaxBazarov** [comment]
Ok,  implemented in 11.5.4
Now Element Inspector shows Style Source and Symbol Source sections.
