### ISSUE TITLE
Scrollbars show on modal dialogs

### ISSUE THREAD

**Issue by axlemax** [ingrammicro/puzzle-publisher#12]
When using an artboard as a modal dialog to display over another artboard, a scrollbar is shown when the generated files are viewed in a web browser, even when the content in the modal artboard is much smaller than the artboard being covered. The artboard for the modal dialog is sized to fit the content it contains, so this should not happen.

This happens in both Firefox and Chrome on Mac OS X.

Options selected for the art board:
- "Show modal dialog or overlay shadow" - checked
- "Scroll browser page to top" - checked
- No delay time is set.

Custom dimensions are not set for the artboard HTML export. The original artboards (that are covered by the modal dialogs) are 1370px x 1024px (WxH), and they are configured as regular pages, with "Scroll browser page to top" checked. However, the scrollbars still show if the underlying artboards are resized.

If the CSS "overflow-y" property is removed on the ".contentModal" class, the scrollbar goes away and the content fits as expected.

**Comment by MaxBazarov** [comment]
Thanks for report. I will fix it.

**Comment by MaxBazarov** [comment]
Fixed in 11.6.1
