### ISSUE TITLE
[Feature Request] Show more style details in inspector. 

### ISSUE THREAD

**Issue by josh-tt** [ingrammicro/puzzle-publisher#15]
Feature Request: Show more style details in the inspector. 

Would be convenient/helpful to see the style details in the inspector.

For example, color as hex (fill/border etc) and font info (size/typeface/weight etc.). I'm guessing that's already detected by PP, so why not display it as additional info.

**Comment by MaxBazarov** [comment]
Josh, the latest PP update does it!

**Comment by josh-tt** [comment]
Nice one, thanks as always! Will check it out :)

**Comment by MaxBazarov** [comment]
The next update will also show margins between layers.
