### ISSUE TITLE
[Feature request] Export to JPG instead of PNG

### ISSUE THREAD

**Issue by hexcross** [ingrammicro/puzzle-publisher#19]
I would love if I can export prototype to HTML with JPG images because PNG are very large. Thanks.

**Comment by MaxBazarov** [comment]
Valid point. I think it just one setting. Will check it today

**Comment by MaxBazarov** [comment]
Done
https://spectrum.chat/puzzle-publisher/general/12-3-0-released~23512686-f81b-492e-9d5b-d5765ae82ead

But probably you will not be happy, because JPG files takes slighly more space than PNG files :(
I can't control compression quality for JPG

**Comment by hexcross** [comment]
It is much better now - from 94,6MB to 22,8MB :) with retina! With compression it will be slightly better but for now it is huge difference from PNG. Me and my FTP thanks a lot for JPG option!

**Comment by MaxBazarov** [comment]
Great to hear it!
Enjoy.
