### ISSUE TITLE
SSH Port when Publishing

### ISSUE THREAD

**Issue by diego-vieira** [ingrammicro/puzzle-publisher#20]
Hi, loved the idea of this plugin.

Is there a way to set a port for SSH connection?

I have tried rsync format without success - e.g. `-e "ssh -p 3384"`

Thanks

**Comment by MaxBazarov** [comment]
Not sure that’s possible right now.
But I can support it. Stay tuned

**Comment by MaxBazarov** [comment]
@diego-vieira 
Done in 12.5.0
https://spectrum.chat/puzzle-publisher/general/12-5-0-released~0db96bd8-d260-4412-8d8c-da8ed831a55a
