### ISSUE TITLE
[Feature Request] GitHub pages support?

### ISSUE THREAD

**Issue by jasoncypret** [ingrammicro/puzzle-publisher#21]
With Sketch Cloud being so unreliable this plugin is super solid. Have you considered using git & github pages as an option alongside FTP?

**Comment by MaxBazarov** [comment]
Yes. I have a plan to support Github pages. But have no any solid estimations yet.

**Comment by MaxBazarov** [comment]
@jasoncypret  What exactly do you mean by "GitHub pages support"? You can just export a prototype to Git folder and run git push.
