### ISSUE TITLE
Document color option in settings is not visible

### ISSUE THREAD

**Issue by jessedobbelaere** [ingrammicro/puzzle-publisher#23]
![image](https://user-images.githubusercontent.com/1352979/89320941-82fe0700-d682-11ea-9498-3136c2f1baf9.png)

Was hoping to set a custom document color in this document settings dialog but it looks cut-off, and I cannot resize the window either. Could not get the `@MainBackground@` to work either :( I can probably set it to a white background by injecting some css anyway, but wanted to notify if this is not normal behaviour. 

I'm using Sketch Version 67.2 (100443)

**Comment by MaxBazarov** [comment]
Ooops. Fixed in 14.7.2
Please update the plugin

**Comment by jessedobbelaere** [comment]
Thanks for the quick fix! 🙌
