### ISSUE TITLE
Possibility to ignore artboards

### ISSUE THREAD

**Issue by jessedobbelaere** [ingrammicro/puzzle-publisher#24]
Is it possible to ignore certain artboards (e.g. symbols etc)? In InvisionApp you can prefix pages or artboards with `-` to [ignore certain artboards](https://support.invisionapp.com/hc/en-us/articles/115004504186-How-do-I-exclude-artboards-from-syncing-in-Craft-Sync-). Or maybe I looked over the option in the docs?

**Comment by MaxBazarov** [comment]
Yes. You can use *

**Comment by jessedobbelaere** [comment]
Awesome, thank you!
