### ISSUE TITLE
How to Generate index.html?

### ISSUE THREAD

**Issue by is7l** [ingrammicro/puzzle-publisher#25]
hi ,
I have a question to ask you.
I now want to implement an export with all the files on index.html, Then upload it to our server. 
But there's no way to start, What should I do first?
Thanks.

**Comment by MaxBazarov** [comment]
Did you try to select «Export to HTML» menu option?

**Comment by MaxBazarov** [comment]
So, you are going to create your own plugin.
What do you want from me? I already created my own plugin for exporting.

**Comment by is7l** [comment]
I want to know the whole process of generating HTML for it, 
so go ahead,
Please .

**Comment by MaxBazarov** [comment]
No problem. Just learn my source code.
