### ISSUE TITLE
"Export failed with errors"

### ISSUE THREAD

**Issue by cargeo** [ingrammicro/puzzle-publisher#26]
When exporting artboards to HTML I get the following error:

"Export failed with errors
TypeError: undefined is not an object (evaluating 'res.ln')"

Sketch 69.2
Puzzle Publisher 14.10.3

**Comment by MaxBazarov** [comment]
Sorry. Fixed in 14.10.4

**Comment by MaxBazarov** [comment]
Please test it and answer - did I fix you problem?

**Comment by cargeo** [comment]
Works. Thank you.
