### ISSUE TITLE
Checkbox "Open HTML in Browser"

### ISSUE THREAD

**Issue by cargeo** [ingrammicro/puzzle-publisher#27]
Checkbox "Open HTML in Browser" doesn't work. It opens HTML export in Browser even if checkbox is unchecked.

**Comment by MaxBazarov** [comment]
Confirmed. Is it critical for you or can wait for the next Monday?
(I'm on vacation right now :)

**Comment by cargeo** [comment]
Not critical at all. Take your time.

**Comment by MaxBazarov** [comment]
Fixed in 14.11.0
