### ISSUE TITLE
Does the plugin make any network requests?

### ISSUE THREAD

**Issue by endquote** [ingrammicro/puzzle-publisher#29]
I'm trying to determine if the plugin makes any analytics requests or shares any data over the network, for security reasons.

I see a bunch of PHP in [server_tools](https://github.com/ingrammicro/puzzle-publisher/tree/master/server_tools), does that run in the cloud somewhere?

**Comment by MaxBazarov** [comment]
By default it runs only Google Analytics. You can disable it in the plugin configuration.

PHP files in server_tools and comments folders _can_ be manually installed on your server and enabled in the plugin configuration.

**Comment by endquote** [comment]
Thanks!
