### ISSUE TITLE
Define viewing order

### ISSUE THREAD

**Issue by formap** [ingrammicro/puzzle-publisher#3]
Hello!

I'm not sure if there's currently a way to do this, I don't think there is but correct me if I'm wrong. 

It would be a nice feature if we could be able to define an order for when we view artboards. 

Just throwing the idea here. 

Thanks for the plugin! :)

**Comment by MaxBazarov** [comment]
Hello.

Actually you could do it. But it was broken in 11.0.0 release :)
I just released 11.0.2 in order to fix it.

You can specify a default sort order for all documents, or setup custom sort order for a single document.






Is it that you asked about?
