### ISSUE TITLE
Export failed with errors

### ISSUE THREAD

**Issue by yiching** [ingrammicro/puzzle-publisher#35]
TypeError: null is not an object (evaluating 'attributes. MSAttributedStringColorAttrubute.swatchID')

**Comment by MaxBazarov** [comment]
Please enable debug in Configure Plugin and send me a two last log pages.
https://github.com/ingrammicro/puzzle-publisher/blob/master/Hints.md#hint5

**Comment by yiching** [comment]
```
Chende-MacBook-Pro-3:~ Yiching$ tail -f ~/Library/Logs/com.bohemiancoding.sketch3/Plugin\ Log.log
10:0.54 exportArtboards: running...
10:0.58 [ ERROR ] TypeError: null is not an object (evaluating 'attributes.MSAttributedStringColorAttribute.swatchID')
10:0.59 exportArtboards: done!
closing...
closed
10:39.30 exportArtboards: running...
10:39.33 [ ERROR ] TypeError: null is not an object (evaluating 'attributes.MSAttributedStringColorAttribute.swatchID')
10:39.34 exportArtboards: done!
closing...
closed
```

**Comment by MaxBazarov** [comment]
Thanks.
I just released 16.2.3 with workaround applied. Please try.

**Comment by MaxBazarov** [comment]
@yiching Did you try again?

**Comment by yiching** [comment]
yes, it passed!
But some of prototyping links are not work. I fixed it by deleting these 'objects' (delete prototype link doesn't work) and re-create objects with prototype link. Thanks.

**Comment by MaxBazarov** [comment]
Nice. Regarding links - please send me some example at the next time.
