### ISSUE TITLE
Symbols crash after file export hang

### ISSUE THREAD

**Issue by yiching** [ingrammicro/puzzle-publisher#38]
Sometimes my file export hanging, and symbols in file will be crash.
Symbols became folders and can not be controlled by Symbols page.
I fix my files several times (create symbols again and replace those folders), but waste times.
Are there any idea for this issue?

symbol folder example as below
![image](https://user-images.githubusercontent.com/4469564/120728020-90885580-c50e-11eb-9d4b-2c41f7470cf7.png)

**Comment by MaxBazarov** [comment]
Hello.
1) it shouldn’t crash. If it does so then I need to fix it. Please send me the last page of log file after the next crash.
2) currently Publisher convert all symbols to groups during the exporting and roll back it right after the process. If it crashed then roll back can not be executed. You can do it manually - just select Undo changes in Sketch menu
3) I’m waiting a bug fix from Sketch team and change the plugin workflow in a way which will prevent such symbol transformations

Thanks for feedback!

**Comment by MaxBazarov** [comment]
No response from the reporter
