### ISSUE TITLE
[Feature Request] Enable "Enable Element Inspector" for "Export selected to HTML" dialog

### ISSUE THREAD

**Issue by samsonw** [ingrammicro/puzzle-publisher#47]
In the latest version ([16.7.0](https://github.com/ingrammicro/puzzle-publisher/commit/3e0ce159017efa281b2df1819485f8aad1d0d26f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)) the "Enable Element Inspector" option has been moved to Export dialog, can it be supported at "Export selected to HTML" dialog as well, thanks!

**Comment by MaxBazarov** [comment]
Oops. It’s my fail. Will be fixed ASAP.

**Comment by MaxBazarov** [comment]
@samsonw  I'm sorry, but directly after the "Export selected to HTML" dialog a user sees "Export to HTML" dialog with "Enable Element Inspector".

**Comment by samsonw** [comment]
Oh yes, i just realized this, thanks for the clarification.
