### ISSUE TITLE
„Press S to „Go to Start“

### ISSUE THREAD

**Issue by Nevu** [ingrammicro/puzzle-publisher#48]
Hi,

I have a little flow and a „flag“-marker in starting page.
But when pressing „S“ I only „return“ somewhere in the middle.

Does this behavior depend on any y- or x-axis?

Regards

**Comment by MaxBazarov** [comment]
The sort order can be changed in Configure Plugin or Configure Document dialogs.
<img width="523" alt="Screenshot 2021-08-19 at 20 36 52" src="https://user-images.githubusercontent.com/18418306/130117123-a1fc6910-c4b6-4da1-9438-b25df5810042.png">

But you right, "S" button should return to real start page marked as "Start Point". I need to fix it.

**Comment by MaxBazarov** [comment]
@Nevu 
Fixed in 16.7.4
