### ISSUE TITLE
Transparent layers shown white

### ISSUE THREAD

**Issue by Nevu** [ingrammicro/puzzle-publisher#51]
Hi,

they is a nasty layer-issue.
When using layers, groups, element (also when using them as symbols) they seem to generate a white background.

How to fix this issue?

<img width="991" alt="img" src="https://user-images.githubusercontent.com/2456068/131871959-9a64d743-dabb-42b2-b876-bb1f8057c19e.png">

[layer-issues.zip](https://github.com/ingrammicro/puzzle-publisher/files/7100030/layer-issues.zip)

**Comment by Nevu** [comment]
Typo also seems to be a little bit „squeezed“ ...

**Comment by MaxBazarov** [comment]
@Nevu  Are exporting to PNG to JPG?
JPG doesn't support transparency :(

**Comment by Nevu** [comment]
The issue tappend, when sei the Typo to „fixed Position“
[puzzle.zip](https://github.com/ingrammicro/puzzle-publisher/files/7745165/puzzle.zip)

[Archiv.zip](https://github.com/ingrammicro/puzzle-publisher/files/7745161/Archiv.zip)
