### ISSUE TITLE
Proper sticky bottom elements

### ISSUE THREAD

**Issue by Nevu** [ingrammicro/puzzle-publisher#69]
Hello,

is there a possibility to create a sticky _bottom_ navigation in a proper way?

I just hacked it a bit with top-sticky reference, but would be cool to have a proper way.

Regards

<img width="1517" alt="img" src="https://user-images.githubusercontent.com/2456068/145191258-d07eeba6-9c13-461a-aee5-b734e72761d1.png">

**Comment by Nevu** [comment]
[bug-sticky-element-SKETCH.zip](https://github.com/ingrammicro/puzzle-publisher/files/7675979/bug-sticky-element-SKETCH.zip)
[bug-sticky-element-PUZZLE.zip](https://github.com/ingrammicro/puzzle-publisher/files/7675980/bug-sticky-element-PUZZLE.zip)

**Comment by MaxBazarov** [comment]
Reviewing....

**Comment by MaxBazarov** [comment]
@Nevu You just need to pin it to bottom.
<img width="830" alt="Screenshot 2021-12-08 at 18 45 34" src="https://user-images.githubusercontent.com/18418306/145238485-d675ff59-116d-47aa-af57-0d28ccee6163.png">

Please try.

**Comment by Nevu** [comment]
Works. Great. Thanks!
I share this „trick“
