### ISSUE TITLE
Export failed with errors

### ISSUE THREAD

**Issue by yiching** [ingrammicro/puzzle-publisher#7]
`Type Error: undefined is not an object (evaluating 'this.symbolMaster.getLibrary')`
This error message show while exporting artboards with symbols. How to fix it?

**Comment by MaxBazarov** [comment]
Let me check it

**Comment by MaxBazarov** [comment]
Could you share your file with me? 
mbazarov@gmail.com
If you can't then I will try to fix it in some other way.
