### ISSUE TITLE
Links/Hotspots not working inside symbols

### ISSUE THREAD

**Issue by studioduda** [ingrammicro/puzzle-publisher#73]
Thanks for this awesome plugin! It's everything i was looking for!
Unfortunately any kind of links **used in Symbols** isn't working in the latest release. It has worked before using 16.17.1.
Links in Artboards work as expected.

**Comment by MaxBazarov** [comment]
Hello.
Ok thanks for information.
Will investigate the issue today.

**Comment by MaxBazarov** [comment]
Do you have the setting enabled?

**Comment by MaxBazarov** [comment]
17.0.3 fixed the issue.
@studioduda  Please verify.

**Comment by studioduda** [comment]
@MaxBazarov  Yes, it's fixed - thanks a lot!

**Comment by MaxBazarov** [comment]
Nice
