### ISSUE TITLE
Can't export the right artboard

### ISSUE THREAD

**Issue by caipod** [ingrammicro/puzzle-publisher#74]
My sketch can't export the selected art boards to html via puzzle publisher instead the plug-in exports all the art boards in the sketch document.

Sketch version: 83.2 
Puzzle version :17.0.3
OS version : Big Sur 11.6.4

**Comment by MaxBazarov** [comment]
Thanks for the report.
Will be fixed soon.

**Comment by MaxBazarov** [comment]
Sorry, but still in progress.

**Comment by MaxBazarov** [comment]
@caipod  Fixed in 17.0.5
Sorry for delay

**Comment by caipod** [comment]
> @caipod Fixed in 17.0.5 Sorry for delay

Thank you very much!

**Comment by MaxBazarov** [comment]
@caipod  Always welcome.
Also check the similar my plugin, for Figma — https://www.figma.com/community/plugin/1033284895522313541/Demo-Station
