### ISSUE TITLE
Hotspots with Previous Artboard target only works once

### ISSUE THREAD

**Issue by habovh** [ingrammicro/puzzle-publisher#75]
I have a project where the user can go deep in the screens (artboard) hierarchy, and each screen in the hierarchy has a "back" button that allows the user to get back to the starting or "root" artboard.

It works fine when running prototype within Sketch, but when exported using Puzzle Publisher, it seems the back button only brings back to the previously **displayed** artboard. Instead of going back up the hierarchy much like `history.back()`, clicking the back button works once, but clicking again brings back the artboard we just left.

Consider the following artboards A, B, C and D. Root is A. Goal is to get from A down to D through B and C, then go back up. The arrow "→" means a "push" to the next artboard. The return arrow "↩" means pressing the back button.

**Expected behaviour**
A → B → C → D ↩ C ↩ B ↩ A

**Actual behaviour**
A → B → C → D ↩ C ↩ D ↩ C ↩ D ↩ C

As you can see, pressing back multiple times only swaps between the last two screens whereas it is expected to navigate back in the history.

From what I understand reading how the `goBack` function works:

https://github.com/ingrammicro/puzzle-publisher/blob/59f4db287f4ef3abb0390ec5de957df2358007cf/PuzzlePublisher.sketchplugin/Contents/Sketch/viewer/viewer.js#L633-L642

It seems that Puzzle Publisher is either:
- not storing the stack properly when navigating down;
- mistakingly considering my artboards for modals.

FYI, I'm using the "Animate artboard from right" setting on when pushing a screen and "No artboard animation" when going back.

**Comment by MaxBazarov** [comment]
@habovh  Thanks for the report. 
Investigating...

**Comment by habovh** [comment]
@MaxBazarov wow that was fast! It seems that the back button behaviour is working as expected now, thank you!

Out of curiosity, how do modal works in the context of this plugin? Is there a special way to push artboards that marks them as modals?

**Comment by MaxBazarov** [comment]
> Out of curiosity, how do modal works in the context of this plugin? Is there a special way to push artboards that marks them as modals?

You can set Modal type in Configure artboard. Partially it mean that that artboad will displayed on a center over previous  page  with full-page shadow. 
<img width="1238" alt="Screenshot 2022-03-31 at 20 58 00" src="https://user-images.githubusercontent.com/18418306/161120249-57c13589-1903-4382-98d7-d4f4f640a657.png">
<img width="624" alt="Screenshot 2022-03-31 at 20 58 12" src="https://user-images.githubusercontent.com/18418306/161120257-3eaed294-eb15-4294-a9cb-0d1916f0c6e4.png">

See example here - https://github.com/ingrammicro/puzzle-publisher/tree/master/examples/Link-ModalArtboard

**Comment by habovh** [comment]
Thanks for the info, I wasn't aware of this! Will definitely come in handy down the line.
