### ISSUE TITLE
Publish Not Uploading Updated Artboards

### ISSUE THREAD

**Issue by nickian** [ingrammicro/puzzle-publisher#8]
I noticed that when I publish a document via SFTP, then update the document and publish a v2, the original artboard is uploaded again. My Sketch document is updated and saved, but the published prototype on my server is still displaying the original that I uploaded. Is it cached somewhere? I cleared my browser cache. This is not happening when I simply export HTML locally.

**Comment by MaxBazarov** [comment]
"Publish" command just publish already generated files.
So, if you did some changes and want to publish it then you need to run "Export to HTML" before publishing.

**Comment by MaxBazarov** [comment]
Probably it's no quite clear and needs to be improved.

**Comment by nickian** [comment]
Ah, I see. I was imagining that "publish" created HTML then published, but it simply publishes the HTML that you have to export first?

**Comment by MaxBazarov** [comment]
Yes.
